# SPDX-FileCopyrightText: 2023 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = ".gitignore"
precedence = "override"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "None"

[[annotations]]
path = ".readthedocs.yaml"
precedence = "override"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "None"

[[annotations]]
path = "docs/_static/*.css"
precedence = "override"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "None"

[[annotations]]
path = "docs/_static/esplogosmall.bmp"
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 1989, 1991 Free Software Foundation, Inc."
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = "docs/Makefile"
precedence = "override"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "None"

[[annotations]]
path = ["docs/*.rst", "examples/*.rst"]
precedence = "override"
SPDX-FileCopyrightText = "2017 Free Software Foundation Europe e.V. <https://fsfe.org>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "docs/esprsim/*.rst"
precedence = "override"
SPDX-FileCopyrightText = "2017 Free Software Foundation Europe e.V. <https://fsfe.org>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "examples/detailed_model/**"
precedence = "override"
SPDX-FileCopyrightText = "esprsim contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "examples/simple_model/**"
precedence = "override"
SPDX-FileCopyrightText = "esprsim contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "src/esprsim.egg-info/**"
precedence = "override"
SPDX-FileCopyrightText = "2017 Free Software Foundation Europe e.V. <https://fsfe.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "src/esprsim/__about__.py"
precedence = "override"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "None"
